### ISSUE TITLE
Disabling the copy option for expression on canvas

### ISSUE THREAD

**Issue by Sameedha** [eweitnauer/gm-play-iub-2017#1]
We would like to know if there are any flags which we can use to control supported operations on canvas.
Few of the operations which we would like to control are -
1) Copy
2) Show previous operation in hierarchy

**Comment by eweitnauer** [comment]
In the [API docs](https://github.com/eweitnauer/gm-api/blob/master/API.md), the `Derivation` has an option called `"clone_on"`, which controls whether derivations can be copied by the user by dragging and dropping a line handle. Is that what you are talking about?

I am not sure what you mean by your point 2. There is a derivation option `"collapsed_mode"` that controls whether the derivation starts in a mode where new lines will automatically collapse.
