### ISSUE TITLE
Variable font size in GM Canvas

### ISSUE THREAD

**Issue by shreeharshas** [eweitnauer/gm-play-iub-2017#111]
Since the rocks (and eggs) game pieces display using GM canvas, the automatic width control provided by Phaser cannot be used.
The GM canvas renders text with uniform size for all rocks independent of their equation length by default in **px** unit

Due to this, some rocks have their equations overflowing out into the background.

We tried the following methods to address this issue:
**1. Setting smaller font size:**
- By setting the font size to a lesser value, we were able to get the equations proper on initial levels having simple equations however higher levels with more terms still had the overflowing issue.

**2. Calculating the font size based on number of characters in the equation:**
- This was successful in avoiding the text overflow but the equations were too small in the first three levels and too big in the next three. Moreover, figuring out a generic formula is itself challenging due to unpredictable terms in the equation and also not feasible in the long run.

**3. Calculating the font size based on the font values:**
- Tried considering the size taken by one letter and formulating the size based on this but since Kalam font is variable spaced (the characters i and l take less space than m or w) unlike monospaced fonts such as Courier, this method is not feasible.

**4. Using CSS3 "@media" property to set the size:**
- This was overridden by the javascript value given during derivation creation. Even this may not work as it sets discrete font size values instead of variable size.

**5. Using "em", "%", "vw" instead of px**
- Faced exception - these don't seem to be available.

Therefore, request you to enable support for auto font size properties such as "em" or "%" in addition to the existing "px" or if already supported, please provide documentation on using it.

**Comment by eweitnauer** [comment]
The best way here is to find out how large an expression is on the screen after you render it and then adjust the font-size accordingly to make it fit a box. Since this seems like a really useful functionality, [we will create an API call for it](https://github.com/eweitnauer/gm-play-iub-2017/issues/124).

If you want to work on it yourself in the meantime, there is an API call "getBBox()" that you can use on an AlgebraView like this: `derivation.getLastView().getBBox()`.

**Comment by eweitnauer** [comment]
This is solved in issue https://github.com/eweitnauer/gm-play-iub-2017/issues/124 now!
