### ISSUE TITLE
Multiple symbols wiggle for tutorial pair

### ISSUE THREAD

**Issue by shreeharshas** [eweitnauer/gm-play-iub-2017#112]
In an equation having 2 or more "+" or "-" signs, if we set wiggle to one of them, then all the signs will wiggle which will confuse the player.

![image](https://cloud.githubusercontent.com/assets/8735082/24840251/bf143636-1d37-11e7-9a7d-1b3cf5524174.png)

**Comment by eweitnauer** [comment]
You can use this syntax "+:1" to specify that the nth "+" should wiggle.
