### ISSUE TITLE
Do some more browser testing and fixing

### ISSUE THREAD

**Issue by eweitnauer** [eweitnauer/gm-play-iub-2017#125]

**Comment by shreeharshas** [comment]
Will add browser specific css

**Comment by shreeharshas** [comment]
Firefox does not play the tutorial. Logging error to console showed gm api error as per the screenshot:
![image](https://cloud.githubusercontent.com/assets/8735082/25557375/033f0560-2cde-11e7-9059-3fda58778bb5.png)

**Comment by shreeharshas** [comment]
Also checked the tutorial using visibility css instead of display but the problem still persists.

**Comment by shreeharshas** [comment]
No other issue found except the existing tutorial bug tracked with Issue #165, hence closing.
