### ISSUE TITLE
Hiding equations based on the context

### ISSUE THREAD

**Issue by shreeharshas** [eweitnauer/gm-play-iub-2017#136]
The egg equations must be hidden during the rock waves. The equations should only be visible when the player chooses to hatch an egg. After picking & during solving, only that egg should show its equation.

**Comment by Sameedha** [comment]
This issue is fixed in demo_11. 
The fix is already pushed to sam_demo11. A pull request needs to be created and merged into master.

**Comment by Sameedha** [comment]
The fix is pushed in master branch
