### ISSUE TITLE
Multiple overlapping equations

### ISSUE THREAD

**Issue by shreeharshas** [eweitnauer/gm-play-iub-2017#138]
Bug after hatching an egg:

![3b7a1af6-2053-11e7-8d87-3571f9711de2](https://cloud.githubusercontent.com/assets/8735082/25029718/ee9419ea-208d-11e7-81bc-8e7de9dd98c1.png)

**Comment by LaxmiBhavaniM** [comment]
Fixed in GM API v2.0.1. #157
