### ISSUE TITLE
Add tutorial for gradeset 2

### ISSUE THREAD

**Issue by shreeharshas** [eweitnauer/gm-play-iub-2017#141]

**Comment by shreeharshas** [comment]
Since the problems have been updated with capital letters, should we also update the tutorials accordingly? If so, we will update tutorials for both the grade sets.

**Comment by eweitnauer** [comment]
Only the letters for the lower grade level should be capitalized, so only those tutorials need to be updated. The tutorials might have to be recorded with the correct option for the multiplication symbol.

**Comment by shreeharshas** [comment]
Sure, I will start work on it when the multiplication symbol is available. Thank you.

**Comment by shreeharshas** [comment]
Completed by pull request #186 
Changes made:

1. Updated code to support two sets of tutorial pairs corresponding to the gradesets
2. Updated the format of the JSON data to hold the two gradesets data
3. Added relevant tutorial pairs
4. Removed redundant tutorial pairs
5. Capitalized set 1 pairs
6. Included the new multiplication symbol
