### ISSUE TITLE
Improved egg colors

### ISSUE THREAD

**Issue by eweitnauer** [eweitnauer/gm-play-iub-2017#184]
Please try these egg colors:

![image](https://cloud.githubusercontent.com/assets/53043/25485658/aa2fd79a-2b2c-11e7-962a-4a747e205745.png)

1. normal color
2. `#FFB030`
3. `#B44B00`
4. `#670900`

**Comment by LaxmiBhavaniM** [comment]
@eweitnauer The new egg colors are similar to the golden egg color. Please let us  know if that is fine.

**Comment by LaxmiBhavaniM** [comment]
![image](https://cloud.githubusercontent.com/assets/15314579/25499497/abfc23a8-2b59-11e7-855a-8c90b82abebd.png)

**Comment by eweitnauer** [comment]
I thought about that, too...

The best solution would be to not change the colors, but instead put
bandages on the eggs that got hit. But let's not do this for Monday, it is
too much work to do that for all the animations!

Instead, we could make the golden egg a little bigger to distinguish it! Is
it hard to make the golden egg +20% larger?
I'll additionally adjust the egg colors a little to make them more orange.

**Comment by eweitnauer** [comment]
Here are the new colors:

- `#FF8D28`
- `#B64C00`
- `#681D00`

**Comment by eweitnauer** [comment]
These are probably different enough from the golden egg! So if it is a big headache to make the golden egg bigger, don't worry about it. It would make sense of course -- enough space for three babies ;)

**Comment by LaxmiBhavaniM** [comment]
Resizing the golden egg messes its GM derivation positioning. We have updated the egg colors instead.
