### ISSUE TITLE
Events for invalid operation performed on Canvas

### ISSUE THREAD

**Issue by Sameedha** [eweitnauer/gm-play-iub-2017#2]
Is it possible to get logs for invalid operations performed on Canvas ? As discussed in our previous meeting (02/01/2017), this is an enhancement.

**Comment by eweitnauer** [comment]
There is a `mistake` event that you can listen to on a `Derivation` like this: `derivation.events.on('mistake', callback);`. The event will be fired if the user clicks on a term, but does not trigger an action. This happens, for example, when clicking on the `+` in `2+3*4`, but also when clicking on `10` in `10`, or on `x` in `x=2` or on `1` in `1+2`.

I added this information to the [API docs](https://github.com/eweitnauer/gm-api/blob/master/API.md).

The event does not contain any useful information about where the user clicked. Please let me know if you need such information for a game.
