### ISSUE TITLE
Need more documentation on Algebra Row and Algebra Model

### ISSUE THREAD

**Issue by Sameedha** [eweitnauer/gm-play-iub-2017#3]
It would be great if we can find some more documentation or example code snippet for Algebra Row and Model.

**Comment by eweitnauer** [comment]
Please be more specific on what you want to accomplish.

**Comment by Sameedha** [comment]
Hi Erik,

We would like to know for what operations we can use AlgebraRow and Model. We are wondering if there is anything special we can do by using them which can't be done with usual html operations.
We understand that we may not need this for now, but there may be a use case for future. In that case, we will again get back to you.

Thanks,
Sameedha

**Comment by Sameedha** [comment]
We may not need this anymore.
Thanks.
