### ISSUE TITLE
Refine game over criteria

### ISSUE THREAD

**Issue by Sameedha** [eweitnauer/gm-play-iub-2017#34]
Criteria for game over 

1. All eggs hatched.
2. Time is up.
3. All rocks are spewed from the volcano and destroyed (no more rocks are visible on game canvas).

**Comment by shreeharshas** [comment]
/*game over scenarios and scoring scheme*/

score = number of equations solved

if time is up   //code for this block to be placed in the file gamePlay.js where the remaining time is being checked
	if any egg is remaining
		player lost
	else
		if any rocks are remaining
			add remaining number of rocks to the score
			player won
		else
			//nothing to add to score
			player won
	
else     //code for this block to be placed in the file gamePieces.js where the game loop keeps running
	if any egg is remaining
		if any rocks are remaining
			//time, rocks and eggs are all present so the game continues
		else
			//time and eggs remain but rocks are over
			add remaining time to the score
			add remaining number of eggs to the score
			player won
	else
		if any rocks are remaining
			//time and rocks remain but eggs are over
			add remaining time to the score
			add remaining number of rocks to the score
			player won
		else
			//time remains but rocks and eggs are over
			add remaining time to the score
			player won

**Comment by shreeharshas** [comment]
Tested and OK
