### ISSUE TITLE
Code Refactoring

### ISSUE THREAD

**Issue by singhPrasan** [eweitnauer/gm-play-iub-2017#35]
1. Remove dead code Eg min and sec - remove min, sec variable custom expression.js
2. Remove hardcoding
3. Rename variables following a convention Eg global variable without var keyword and with g_
4. Create canvas tag in html to set height and width
5. Remove g_dino.move() function call

**Comment by LaxmiBhavaniM** [comment]
Moved to Phaser. Code structure changed.
