### ISSUE TITLE
Need to access HTML elements inside GM canvas to use during Tour

### ISSUE THREAD

**Issue by Sameedha** [eweitnauer/gm-play-iub-2017#4]
We would like to point to specific HTML elements withing GM Canvas while showing tour. As discussed, this is already supported in the demo(s) shown on GM website. If we can find an example code snippet, it would be of great help.

**Comment by eweitnauer** [comment]
To wiggle a particular node, you can call either call `derivation.startWiggle(sels)` and pass a term selector string to the method. Node selectors consist of an ascii part that describes the term, and optionally a colon to select the nth occurrence. For example, you could call `derivation.startWiggle('+:2')` to wiggle the second '+' in a derivation's last line.

I added this to the API documentation.

Let me know if this works or if you really need to access the html elements that correspond to particular terms. There are also ways to change the color (highlight) particular terms, if you want to do that.

**Comment by Sameedha** [comment]
Thanks
