### ISSUE TITLE
Multiplication with Zero (Equation Solving)

### ISSUE THREAD

**Issue by singhPrasan** [eweitnauer/gm-play-iub-2017#41]
While solving an equation for x, For instance, if you have **4x + 3 = 3** as the equation. 
In the steps to solve the equation, you will have **4x = 0** as the equation. Next if you do **4 = 0 / x** and drag 0 over 'x'. The equation that is left is **4 = 0**. Which is incorrect solution to the given equation

![1](https://cloud.githubusercontent.com/assets/22266716/23283793/fc9ae4a6-f9f5-11e6-9208-abdc58ea71df.PNG)
![2](https://cloud.githubusercontent.com/assets/22266716/23283794/fca32f94-f9f5-11e6-9748-f0004f6b64f5.PNG)

**Comment by eweitnauer** [comment]
What happens here is that GM generally allows you to do things that generally work, but might not be allowed in special cases. In this case, you divided by `x`, and that is only allowed if `x` is not `0`. Now in the case you show the solution actually *is* `x=0`.

There are several ways to address this. The simplest is to just avoid using equations where this comes up. Another way would be to automatically detect whether the user did something illegal (given your knowledge of what the solution is). Then you could shake the whole equation, turn it red, give a short reason of why that step was not okay and then let the user undo the last step.

**Comment by Sameedha** [comment]
We have refined our problem set and this scenario would not come up now. Hence, closing this issue.
