### ISSUE TITLE
Fractional simplification throws error for GM Canvas. Example 6/10

### ISSUE THREAD

**Issue by lipingsun-dayone** [eweitnauer/gm-play-iub-2017#52]
<img width="1345" alt="screen shot 2017-02-28 at 9 13 07 pm" src="https://cloud.githubusercontent.com/assets/21134818/23488960/c6ef6a08-febd-11e6-98a5-5e504ff710ef.png">

**Comment by lipingsun-dayone** [comment]
When we try to do the fraction simplification on the canvas, for example 6/10, if we click the sign of division, the fraction could be solve, instead, we need to drag the denominator to the numerator position, the it could be simplified, and then click the sign of division, it could be solved.

**Comment by eweitnauer** [comment]
I'll let David Brokaw look into this!

**Comment by dgbrokaw** [comment]
@lipingsun1989 @eweitnauer I've tested simplifying `6/10` in version 0.12.6 like in the image above and in the current version 1.0.2.  Clicking the fraction bar causes the error in 0.12.6 but not in 1.0.2.  Should the group be using the latest version, or should I make a fix to the previous version?

**Comment by eweitnauer** [comment]
They should use the latest version. So this is fixed, it seems :)
