### ISSUE TITLE
Disable advanced actions

### ISSUE THREAD

**Issue by eweitnauer** [eweitnauer/gm-play-iub-2017#53]
One important thing will be to disable advanced actions that the kids don't need but might accidentally trigger. For example, turning `a` into `1/a^-1`, or bringing up the keyboard by shaking a term.

We are working on a list of action names with examples that you can refer to. There is a way to give a blacklist to a canvas to disable certain actions. We might want to have a whitelist instead. We will work on that.

**Comment by eweitnauer** [comment]
We will work on this, but it won't happen this week. So expect this soon after spring break!

**Comment by eweitnauer** [comment]
Using the blacklist is fine, I guess. All we need is a list + short description of all our actions. And a description of how to use the blacklist option.

**Comment by dgbrokaw** [comment]
There is a gist with the action names linked in the README.

**Comment by eweitnauer** [comment]
Let us know if you need help with this one. The idea is to pass a long list of action names to the derivation the player works with. All these actions will be disabled, so the user can't accidentally trigger actions they should not use (e.g. flipping x into 1/x^-1).

**Comment by Sameedha** [comment]
Flipping x into 1/x^-1 is disabled in demo_12. However, I could not find any action which can 
-  avoid bringing the keyboard 
-  avoid bringing only zero on either side (have at least one element on each side).e.g. a + b = c is okay, but a + b - c = 0 should not be allowed. This was one of the requirements provided by David when he was discussing content for Grade Set 2 ( 7 - 9).

**Comment by eweitnauer** [comment]
David's list is missing the keyboard actions. They are:

- 'CombinationRewriteAction' (combine equations)
- 'EquationRewriteAction' (rewrite equation)
- 'ExpressionRewriteAction' (replace an expression with an equivalent one)
- 'FirstLineRewriteAction' (rewrite dl line)
- 'FractionRewriteAction' (extend fraction)
- 'InequalityRewriteAction' (rewrite inequality)

**Comment by eweitnauer** [comment]
Don't worry about disallowing having the "0" all by itself for now. Just don't include these as rock expressions or powerup expressions.

**Comment by Sameedha** [comment]
Thanks for sharing the missing keyboard actions. These actions are added in blacklist in demo_12.
The new GM version is also updated in all the files.
