### ISSUE TITLE
GM Tutorial API

### ISSUE THREAD

**Issue by LaxmiBhavaniM** [eweitnauer/gm-play-iub-2017#58]
Can you provide us with the GM Tutorial API? We wish to integrate it in our game before the start of each level. The tutorial will be similar to the tutorial available on GraspableMath website.
We have gone through the Graspable Math Algebra Recorder and replay functionality. But we are not sure how to integrate it with the game.

![gmtutorial](https://cloud.githubusercontent.com/assets/15314579/23595660/b8adae14-01f1-11e7-8fe2-db572d0a0317.JPG)

Here are a couple of questions:
-Is the first element in the above image, a video component created using Algebra Recorder?
-Is there a way in which we can validate user actions, similar to the feature in the second element of the image above?

**Comment by eweitnauer** [comment]
David is working on this, sorry for the late response. We've been unusually busy the last week.

**Comment by Sameedha** [comment]
Hi David and Erik,

We tried integrating the tutorial similar to the GM website in our game. But, we are facing few issues in the layout of video and trial content (the div tags). Also, we are not sure why the buttons (do it again and try another) does not trigger any event. 
Our code is in 'tutorial' folder , you can run index.html to view the welcome screen, and then clicking on 'tutorial' button will open the tutorial dialog in front of game. 
Additionally, we have attached a screenshot for the current UI of tutorial.

We just saw your response on this thread and will wait for the API. However, it would be great if we can know whether we are on the right track by using 'TutorialPair' and directly integrating it into our HTML element.

Thanks,
Sameedha
<img width="624" alt="screen shot 2017-03-07 at 1 38 06 pm" src="https://cloud.githubusercontent.com/assets/22250973/23672031/5c44457a-033b-11e7-89a9-425ef1db149c.png">

**Comment by eweitnauer** [comment]
David is working on this and will provide a working example later.
I updated the page you can use to record interactions to replay in the tutorial pairs:

https://graspablemath.com/recorder/indexAM.html?eq=a+b+c

**Comment by dgbrokaw** [comment]
I've made a pull request here: https://github.com/eweitnauer/gm-apps/pull/700.
Also: https://github.com/eweitnauer/graspable-math/pull/1065.

**Comment by eweitnauer** [comment]
I updated https://graspablemath.com/recorder/index.html to the newest version.
I also added David's example code to this repository, so you can take a look!
