### ISSUE TITLE
Need API to compare two expressions

### ISSUE THREAD

**Issue by Sameedha** [eweitnauer/gm-play-iub-2017#65]
As discussed in the meeting, we will need API (similar to toAscii()) to compare two expressions.
This may be used to determine whether user matched the correct expression instead of our naive way( where we are using string replace to remove * from the expression).

**Comment by eweitnauer** [comment]
You can now use `gmath.AlgebraModel.areTheSame(am1, am2)` or `am1.isTheSameAs(am2)` where `am1` and `am2` are two AlgebraModel instances.
