### ISSUE TITLE
API to show current and past expression on GM Canvas

### ISSUE THREAD

**Issue by Sameedha** [eweitnauer/gm-play-iub-2017#67]
We would like an API which can be used to handle current and previous state of the expression. When user performs an operation on expression, the new expression should stay at the same place, but the old one should move up. So, at each time of the canvas, two expressions will be visible.

**Comment by eweitnauer** [comment]
I implemented a test version of this and will push it in the next days. Will let you know.

**Comment by eweitnauer** [comment]
We decided not to do this.
