### ISSUE TITLE
How to pass several practice problems to a TutorialPair

### ISSUE THREAD

**Issue by eweitnauer** [eweitnauer/gm-play-iub-2017#85]

**Comment by dgbrokaw** [comment]
https://github.com/eweitnauer/gm-play-iub-2017/pull/103

**Comment by Sameedha** [comment]
We would like to ask how can we use the 'extraExamples' in tutorial json. We want to show a video of '1+2' and then ask user to try '3+5' during practice. Is 'extraExamples' used for this purpose ?

**Comment by Sameedha** [comment]
As discussed with Erik in last meeting, this is not a requirement now. Hence, closing the issue.
