### ISSUE TITLE
Substitution operation support on GM Canvas

### ISSUE THREAD

**Issue by Sameedha** [eweitnauer/gm-play-iub-2017#9]
We would like to know if substitution for 'x' is supported on GM Canvas. For example,
If user solved 4x +6 = 10, then he may want to substitute x = 1 (obtained from previous equation) for 2y  + 9x = 24 to obtain y.

**Comment by eweitnauer** [comment]
We are in the process of switching to a new substitution system. In the old system before version 0.15.0, you substitute by dragging the line handle of a derivation like `x=1` onto `x`es in other derivations.

In the new substitution system starting with version 0.15.0, substitution works by dragging the `x` in `x=1` onto an `x` in another derivation. You can alternatively directly drag the substituting terms, like `1+2` onto any variable, like the `x` in `3x`, to substitute and get `3*(1+2)` in this example.
