### ISSUE TITLE
Use "x" for multiplication sign and avoid variables x and y for the lower grades

### ISSUE THREAD

**Issue by eweitnauer** [eweitnauer/gm-play-iub-2017#91]
I will look into the API for that.

**Comment by eweitnauer** [comment]
Use "×".

**Comment by eweitnauer** [comment]
In version 2.0.1, you can set `gmath.options.use_arithmetic_multiplication_sym` to true or false to influence the appearance of the multiplication dot.

**Comment by eweitnauer** [comment]
Please update to version 2.0.1 and use the arithmetic multiplication symbol option for the lower grades and don't use it for the higher grades. Also, please only use capital letters for all variable names in the lower grades (this looks better with the "×" for multiplication)!

**Comment by Sameedha** [comment]
Is the 'use_arithmetic_multiplication_sym' option available in version 2.0.1 ? Please check the attached screenshot which shows the current gmath options set by default in new version. I tried setting gmath.options.use_arithmetic_multiplication_sym = true which just adds one more property in gmath options, but it has no effect on the GM expression. Please let me know if I am missing out something here.
<img width="928" alt="screen shot 2017-04-21 at 10 34 27 pm" src="https://cloud.githubusercontent.com/assets/22250973/25300685/1fa0bd9e-26e3-11e7-9763-155b96319e63.png">

**Comment by eweitnauer** [comment]
Sorry about that, the change somehow did not make it into the release. I'm just pushing version 2.0.2 that will have it.

**Comment by Sameedha** [comment]
Thanks Erik. We will wait for the next version then.

**Comment by eweitnauer** [comment]
The next version is out, please give it a try.

**Comment by Sameedha** [comment]
[TestMultiplicationSymbol.txt](https://github.com/eweitnauer/gm-play-iub-2017/files/956126/TestMultiplicationSymbol.txt)

I tried using the new version 2.0.2 , but even after setting the property to true, I could not see the effect. Please check attached file and let me know if I am not setting the property correctly.

**Comment by dgbrokaw** [comment]
That file doesn't contain anything.

**Comment by eweitnauer** [comment]
The example worked for me and the multiplication symbol is not right. David will look into it!

**Comment by eweitnauer** [comment]
We figured out what the problem is and are working on a fix.

**Comment by Sameedha** [comment]
Sorry, the file was not uploaded correctly. 
Here is the html content which I tried to verify this issue -
==================================================
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <script src="https://graspablemath.com/shared/libs/gmath/gm-inject.js"></script>
</head>
<title>Graspable Math</title>
<script src="https://graspablemath.com/shared/libs/gmath/gm-inject.js"></script>

<body class="container">
<div>
    <h1>Test Multiplication Symbol<h1>
        <div id='gm-div' style="margin: 20px; height: 400px"></div>       
        <script>
            var canvas;  
            loadGM(initCanvas, { version: '2.0.2'});
            function initCanvas() {
                gmath.options.use_arithmetic_multiplication_sym = true;
                console.log("Printing Gmath options");
                console.log(gmath.options);
                canvas = new gmath.Canvas('#gm-div', {use_toolbar: false, vertical_scroll: false }); 
                canvas.model.createElement('derivation', { eq: "2*4*7", pos: { x: 'center', y: 50 }});    
                canvas.model.on('el_changed', function(evt) {    
                    console.log(evt.last_eq);    
                });
            }   
        </script>     
</body>
</html>

**Comment by Sameedha** [comment]
Sorry, that file was not uploaded earlier.Below is the main script I used for testing -

var canvas;  
            loadGM(initCanvas, { version: '2.0.2'});
            function initCanvas() {
                gmath.options.use_arithmetic_multiplication_sym = true;
                console.log("Printing Gmath options");
                console.log(gmath.options);
                canvas = new gmath.Canvas('#gm-div', {use_toolbar: false, vertical_scroll: false }); 
                canvas.model.createElement('derivation', { eq: "2*4*7", pos: { x: 'center', y: 50 }});    
                canvas.model.on('el_changed', function(evt) {    
                    console.log(evt.last_eq);    
                });
            }

**Comment by Sameedha** [comment]
The new GM version 2.0.3 solves this issue. The new fix would be available in 'finalDemo' folder soon.
